import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <nav style={{ display: 'flex', gap: 12, marginBottom: 16 }}>
            <Link href="/">Home</Link>
            <Link href="/add">Add expense</Link>
            <Link href="/expenses">Expenses</Link>
            <Link href="/map">View Map</Link>
          </nav>
          {children}
        </Providers>
      </body>
    </html>
  );
}
